### ISSUE TITLE
strange behavio(u)r when moving windows between portrait and landscape outputs

### ISSUE THREAD

**Issue by Diax170** [dawsers/scroll#172]
### Please fill out the following:
- **Scroll Version:**
  - `scroll version 1.13-dev-59a71a41 (Dec 25 2025, branch 'master')`

- **Configuration File:**
```
# file: $XDG_CONFIG_HOME/scroll/config.d/outputs2.conf

# vim: ft=swayconfig

output "DP-2" {
    mode  3440x1440@99.982Hz
    pos 1080 355
    transform normal
    scale 1.25
    scale_filter nearest
    adaptive_sync off
    dpms on
}
output "HDMI-A-1" {
    mode  1920x1080@60.0Hz
    pos 0 0
    transform 270
    scale 1.0
    scale_filter nearest
    adaptive_sync on
    dpms on
}
output "eDP-1" disable
exec sleep 2 && scrollmsg 'output eDP-1 enable' && sleep 1 && scrollmsg 'output eDP-1 disable'

workspace 1 output HDMI-A-1
workspace 2 output DP-2
```
  - you should also set `focus_follows_mouse no`

- **Description:**
  - when I **swap** (not just move) windows between portrait and landscape outputs using my mouse, they only get resized properly after focusing them

https://github.com/user-attachments/assets/d702a67d-322d-45cb-b0a3-3383ac368127

**Comment by dawsers** [comment]
Thank you! This should be fixed in 5d40eef0dc146f852fb85c199ac525c146f48426

**Comment by Diax170** [comment]
I'm sorry to say that but I think it's the same or worse
`scroll version 1.13-dev-5d40eef0 (Dec 27 2025, branch 'master')`

https://github.com/user-attachments/assets/1486e51b-3cfa-4052-b855-5d864343e389

**Comment by dawsers** [comment]
You have different layout types on each monitor. The left one is in vertical layout mode, and the right one is in horizontal layout type mode. And you are not "swapping windows", because to swap windows you would press mod and drag from inside the window, not from the titlebar. Also, you can see in the second action you perform, the background of the whole monitor becomes blue, that means you are adding the window to the workspace, not swapping,

I agree there is something wrong when dragging from the scrollbar, with different layout types, but I need to know what you are trying to do, and what your configuration is so I can fix it. If you wanted to simply swap windows, the way to do it is:

Press mod while you click and drag from inside the window (not the titlebar) you want to move to the window you want to swap with, and release the mouse when **only** the inside of the window is blue. If there is "more blue" than the inside, you are either adding it to a top level container or to the top level of the other workspace (as it happens in your second action).

Also, mouse dragging/moving is affected by the mode ("h" or "v"), so *scroll* knows whether you are trying to move the whole column/row or just the window you are clicking on.

When swapping, the configuration of the window also moves with tit. For example, in your first action, the window you try to swap has a height of 0.5, and that is why it only occupies 0.5 of the height of the window in the other monitor, while the other one, which has a height of 1.0, occupies the whole height of the portrait monitor (so that action would be correct).

Please, let me know what you are trying to do and I will replicate it and see what is wrong with what is happening, but I think you are also not doing what you think you are doing.

**Comment by Diax170** [comment]
I am aware that swapping sizes is intended, but as I swap the windows (first action in the footage), both windows are mispositioned and not centered even after focusing them, and when I then append a window to the wide (landscape) workspace instead of swapping, the misaligned window still doesn't fix itself and it overlayed with the normal window. It only fixes when I float and tile it

Also please note that it was hard for me to press key combos as I was also holding the phone to record, that's why I was dragging windows using the titlebars

I'll get a stand/tripod next time



> I think you are also not doing what you think you are doing.

Yeah, kinda. It was when I accidentally moved the window to workspace instead of swapping, but now you see the windows overlaying

Please let me know if you need something else!

**Comment by dawsers** [comment]
OK, I get the reason now, I only mentioned it because I thought maybe you were always using the titlebar to drag.

Another thing is I understand this only happens when you are using different layout types on each monitor (the portrait one is in vertical mode: a column of rows) and the landscape one in horizontal mode (a row of columns).

**Comment by Diax170** [comment]
right, it doesn't happen when both outputs have the same layout

**Comment by dawsers** [comment]
It should be fixed in f735126d4e874df6244f83aa03423e85665cb8dd. Thanks!

**Comment by Diax170** [comment]
appears fixed 👍
